import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Firebase identifiers for this app, per platform.
///
/// Normally generated by `flutterfire configure`. Written by hand here from the
/// `google-services.json` that was supplied, because the CLI needs an
/// authenticated Firebase login this machine does not have. The values are the
/// same ones the CLI would copy across, so re-running it later will produce an
/// equivalent file and can safely replace this one.
///
/// **These are identifiers, not secrets.** Firebase documents that this file
/// contains platform identifiers; the API key here is scoped and restricted by
/// project rules. The thing that must never appear in the app is the Firebase
/// **Admin** private key, which belongs to the backend alone.
///
/// Android and iOS are both configured. Web and desktop are not, and asking for
/// them throws with a message that says so rather than handing Firebase a
/// half-filled configuration.
///
/// iOS additionally needs an **APNs authentication key** (`.p8`) with its Key ID
/// and Apple Team ID uploaded to Firebase Console → Cloud Messaging. Nothing in
/// this file can substitute for that: without it Firebase has no way to reach
/// Apple's servers, and every iOS push silently fails.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Firebase is not configured for web. Run `flutterfire configure` and '
        'add the web app to the Firebase project first.',
      );
    }

    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      final other => throw UnsupportedError(
        'Firebase is not configured for $other.',
      ),
    };
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiKdFIagWDT0S72PtPkOX3jpVajhQ9E7o',
    appId: '1:352098370622:android:b013bda2e86f5fcf4a7d6f',
    // `project_number` in google-services.json is the sender id.
    messagingSenderId: '352098370622',
    projectId: 'resturant-19b77',
    storageBucket: 'resturant-19b77.firebasestorage.app',
  );

  /// From `ios/Runner/GoogleService-Info.plist`.
  ///
  /// The bundle id in that file is `com.tscafe.app`, which must keep matching
  /// `PRODUCT_BUNDLE_IDENTIFIER` — a mismatch produces tokens this Firebase
  /// project cannot deliver to, and the failure is silent.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_vLuIw3p6xXWuV-UeZkMTNADi1s4WRO0',
    appId: '1:352098370622:ios:bf4c99d24f05d4984a7d6f',
    messagingSenderId: '352098370622',
    projectId: 'resturant-19b77',
    storageBucket: 'resturant-19b77.firebasestorage.app',
    iosBundleId: 'com.tscafe.app',
  );
}
